# Generated by Django 5.2 on 2026-09-20 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=40, unique=True)),
                ('client_secret_hash', models.CharField(max_length=64)),
                ('client_name', models.CharField(max_length=100)),
                ('registered_domain', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('third_party', 'Third party'), ('first_party', 'First party')], default='third_party', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_clients',
            },
        ),
    ]
