# Generated by Django 5.2 on 2026-09-20 16:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('persona_context', models.CharField(choices=[('professional', 'Professional'), ('personal', 'Personal'), ('gaming', 'Gaming')], max_length=20)),
                ('scope', models.CharField(max_length=200)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='clients.apiclient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consent_grants',
                'indexes': [models.Index(fields=['user', 'client', 'persona_context', 'revoked_at'], name='consent_lookup_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('user', 'client', 'persona_context'), name='consent_one_active_grant')],
            },
        ),
    ]
