# Generated by Django 5.2 on 2026-09-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RevokedToken',
            fields=[
                ('jti', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('client_id', models.CharField(blank=True, max_length=40)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'revoked_tokens',
            },
        ),
        migrations.CreateModel(
            name='SigningKey',
            fields=[
                ('kid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('public_key', models.TextField()),
                ('algorithm', models.CharField(default='RS256', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'signing_keys',
            },
        ),
    ]
