# Generated by Django 5.2 on 2026-09-20 16:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('attribute_key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('allowed_context', models.CharField(choices=[('professional', 'Professional'), ('personal', 'Personal'), ('gaming', 'Gaming')], max_length=20)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('email', 'Email'), ('url', 'URL'), ('date', 'Date')], default='string', max_length=10)),
                ('label', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'attribute_definitions',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context', models.CharField(choices=[('professional', 'Professional'), ('personal', 'Personal'), ('gaming', 'Gaming')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personas',
            },
        ),
        migrations.CreateModel(
            name='PersonaAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(choices=[('professional', 'Professional'), ('personal', 'Personal'), ('gaming', 'Gaming')], editable=False, max_length=20)),
                ('attribute_value', models.TextField()),
                ('visibility_level', models.CharField(choices=[('public', 'Public'), ('consented', 'Consented clients'), ('private', 'Private')], default='public', max_length=10)),
                ('attribute_key', models.ForeignKey(db_column='attribute_key', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='personas.attributedefinition')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='personas.persona')),
            ],
            options={
                'db_table': 'persona_attributes',
            },
        ),
        migrations.CreateModel(
            name='ContextualName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_value', models.CharField(max_length=150)),
                ('name_type', models.CharField(choices=[('legal', 'Legal name'), ('preferred', 'Preferred name'), ('professional', 'Professional name'), ('username', 'Username'), ('nickname', 'Nickname'), ('religious', 'Religious name')], max_length=20)),
                ('context', models.CharField(choices=[('professional', 'Professional'), ('personal', 'Personal'), ('gaming', 'Gaming')], max_length=20)),
                ('visibility_level', models.CharField(choices=[('public', 'Public'), ('consented', 'Consented clients'), ('private', 'Private')], default='public', max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contextual_names',
                'indexes': [models.Index(fields=['user', 'context'], name='names_user_context_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='persona',
            constraint=models.UniqueConstraint(fields=('user', 'context'), name='persona_user_context_uniq'),
        ),
        migrations.AddConstraint(
            model_name='personaattribute',
            constraint=models.UniqueConstraint(fields=('persona', 'attribute_key'), name='persona_attr_persona_key_uniq'),
        ),
    ]
